controllers:
    resource: ../src/Controller/
    type: annotation

kernmel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/create_token

refresh_token:
    path: /api/authentication_refresh

logout:
    path: /api/logout
